name: Deploy To AWS Staging on Push


on:
  push:
    branches: 
    - main
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       #FIRST Sync the Private S3 Bucket
      #THEN SSH INTO AWS LIGHTSAIL
      - name: Configure SSH
        run: |
          mkdir -p 700 ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.cer        
          chmod 600 ~/.ssh/staging.cer
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.cer
            PubKeyAuthentication yes
            IdentitiesOnly yes
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH }}
          SSH_HOST: ${{ secrets.STAGING_SSH_IP }}
      
      - name: Zip plugin
        env:
          PLUGIN_NAME: jwt-auth   
        run: |
              cd $GITHUB_WORKSPACE/..
              # zip up the source
              zip -r /var/tmp/$PLUGIN_NAME.zip $PLUGIN_NAME -x '*.git*'

      - name: Copy Files
        env: 
          PLUGIN_NAME: jwt-auth
          DEPLOY_DIR: ~/deploy-from-github
          PLUGIN_PATH: /home/bitnami/apps/wordpress/htdocs/wp-content/plugins
        run: |
              scp -v /var/tmp/$PLUGIN_NAME.zip staging:$DEPLOY_DIR
              ssh staging "cd $DEPLOY_DIR;rm -rf $PLUGIN_NAME.backup;sudo mv $PLUGIN_PATH/$PLUGIN_NAME $PLUGIN_NAME.backup;unzip $PLUGIN_NAME.zip; mv $PLUGIN_NAME $PLUGIN_PATH;"

